---

afup:
    displayed_name: afup
    full_name:      Association Française des Utilisateurs de PHP (French PHP Users Group)
    parent:
    picture:        afup.svg
    website:        http://afaup.org
    twitter:        afup
    country:        France
    city:           ~

afup_bordeaux:
    displayed_name: afup Bordeaux
    full_name:      afup Bordeaux (Bordeaux PHP Users Group)
    parent:         afup
    picture:        afup.svg
    website:        http://bordeaux.afup.org/
    twitter:        ~
    country:        France
    city:           Bordeaux

afup_luxembourg:
    displayed_name: afup Luxembourg
    full_name:      afup Luxembourg (Luxembourg PHP Users Group)
    parent:         afup
    picture:        afup.svg
    website:        http://luxembourg.afup.org/
    twitter:        afup_luxembourg
    country:        Luxembourg
    city:           ~

afup_marseille:
    displayed_name: afup Marseille
    full_name:      afup Marseille (Marseille PHP Users Group)
    parent:         afup
    picture:        afup.svg
    website:        http://marseille.afup.org
    twitter:        AFUP_Marseille
    country:        France
    city:           Marseille

afup_nantes:
    displayed_name: afup Nantes
    full_name:      afup Nantes (Nantes PHP Users Group)
    parent:         afup
    picture:        afup.svg
    website:        http://nantes.afup.org
    twitter:        ~
    country:        France
    city:           Nantes

afup_toulouse:
    displayed_name: afup Toulouse
    full_name:      afup Toulouse (Toulouse PHP Users Group)
    parent:         afup
    picture:        afup.svg
    website:        http://toulouse.afup.org
    twitter:        afup_toulouse
    country:        France
    city:           Paris

austinphp:
    displayed_name: austinphp
    full_name:      Austin PHP User Group
    parent:         ~
    picture:        austinphp.png
    website:        http://www.meetup.com/austinphp/
    twitter:        austinphp
    country:        USA
    city:           Austin

brusselsphp:
    displayed_name: BrusselsPHP
    full_name:      Brussels PHP User Group
    parent:         ~
    picture:        brusselsphp.svg
    website:        http://www.brusselsphp.be/
    twitter:        brusselsphp
    country:        Belgium
    city:           Brussels

chiphp:
    displayed_name: Chicago PHP
    full_name:      Chicago PHP User Group
    parent:         ~
    picture:        chi-php.svg
    website:        http://www.meetup.com/Chicago-PHP-User-Group/
    twitter:        ChiPHPUG
    country:        USA
    city:           Chicago

hampshire:
    displayed_name: PHP Hampshire
    full_name:      PHP Hampshire
    parent:         ~
    picture:        hampshire.png
    website:        http://www.phphants.co.uk/
    twitter:        phphants
    country:        UK
    city:           Hampshire

lyon:
    displayed_name: afup Lyon
    full_name:      afup Lyon (Lyon PHP Users Group)
    parent:         afup
    picture:        afup-lyon.svg
    website:        http://lyon.afup.org
    twitter:        afup_lyon
    country:        France
    city:           Lyon

paris:
    displayed_name: afup Paris
    full_name:      afup Paris (Paris PHP Users Group)
    parent:         afup
    picture:        afup-paris.svg
    website:        http://paris.afup.org
    twitter:        afup_paris
    country:        France
    city:           Paris

phppb:
    displayed_name: PHP-PB
    full_name:      PHP-PB (Paraíba PHP Users Group)
    parent:         ~
    picture:        php-pb.svg
    website:        http://php-pb.net/
    twitter:        phppb
    country:        Brazil
    city:           Joao Pessoa

phpem:
    displayed_name: PHPem
    full_name:      PHP East Midlands
    parent:
    picture:        phpem.svg
    website:        http://phpem.uk
    twitter:        PHPem
    country:        UK
    city:           ~

phpnw:
    displayed_name: PHPNW
    full_name:      PHP North West
    parent:
    picture:        phpnw.svg
    website:        http://phpnw.org.uk
    twitter:        PHPNW
    country:        UK
    city:           Manchester

phpsurrey:
    displayed_name: PHP Surrey
    full_name:      PHP Surrey
    parent:         ~
    picture:        phpsurrey.png
    website:        http://phpsurrey.uk
    twitter:        phpsurrey
    country:        UK
    city:           Guildford

php.gent:
    displayed_name: PHP.gent
    full_name:      PHP.gent
    parent:         ~
    picture:        phpgent.png
    website:        http://php.gent
    twitter:        phpgent
    country:        Belgium
    city:           Ghent

phpwvl:
    displayed_name: PHP-WVL
    full_name:      PHP West-Vlaanderen
    parent:         ~
    picture:        phpwvl.png
    website:        http://php-wvl.be
    twitter:        phpwvl
    country:        Belgium
    city:           Roeselare

sweetlakephp:
    displayed_name: SweetlakePHP
    full_name:      SweetlakePHP
    parent:
    picture:        sweetlakephp.svg
    website:        http://sweetlakephp.nl
    twitter:        SweetlakePHP
    country:        NL
    city:           Zoetermeer

zgphp:
    displayed_name: ZgPHP
    full_name:      Zagreb PHP
    parent:         ~
    picture:        zgphp.svg
    website:        http://zgphp.org/
    twitter:        zgphp
    country:        Croatia
    city:           Zagreb

comphppuebla:
    displayed_name: PHP Puebla
    full_name:      PHP Puebla User Group
    parent:
    picture:        php-puebla.png
    website:        http://www.comunidadphppuebla.com/
    twitter:        ComPHPPuebla
    country:        México
    city:           Puebla

istanbulphp:
    displayed_name: Istanbul PHP
    full_name:      Istanbul PHP User Group
    parent:
    picture:        istanbulphp.png
    website:        http://meetup.com/IstanbulPHP/
    twitter:        IstanbulPHP
    country:        Turkey
    city:           Istanbul

phpbenelux:
    displayed_name: PHPBenelux
    full_name:      PHPBenelux
    parent:
    picture:        phpbenelux.png
    website:        https://phpbenelux.eu
    twitter:        PHPBenelux
    country:        Belgium, the Netherlands and Luxembourg
    city:

php-tr:
    displayed_name: PHP-TR
    full_name:      Turkey PHP User Group
    parent:
    picture:        php-tr.png
    website:        https://www.facebook.com/groups/tr.developers/
    twitter:        php_tr
    country:        Turkey
    city:           Istanbul

phpugffm:
    displayed_name: PHPUGFFM
    full_name:      PHP-Usergroup Frankfurt/Main
    parent:
    picture:        phpugffm.png
    website:        http://phpugffm.de
    twitter:        phpugffm
    country:        Germany
    city:           Frankfurt/Main

amsterdamphp:
    displayed_name: AmsterdamPHP
    full_name:      AmsterdamPHP
    parent:
    picture:        amsterdamphp.png
    website:        http://php.amsterdam
    twitter:        amsterdamphp
    country:        Netherlands
    city:           Amsterdam
