services:
    haphpy.user_provider:
        class: AFUP\HaphpyBirthdayBundle\Model\UserProvider
        arguments: [@session, @haphpy.admin_checker]

    haphpy.admin_checker:
        class: AFUP\HaphpyBirthdayBundle\Service\AdminEnabler
        arguments: ['%admins%']

    haphpy.form.contribution_converter:
        class: AFUP\HaphpyBirthdayBundle\Form\Converter\ContributionConverter

    haphpy.path_generator:
        class: AFUP\HaphpyBirthdayBundle\Service\PathGenerator
        arguments: ['%contribution_dir%']

    haphpy.contribution_persister:
        class: AFUP\HaphpyBirthdayBundle\Service\ContributionPersister
        arguments: [@doctrine.orm.entity_manager, @haphpy.path_generator]

    haphpy.file_attacher:
        class: AFUP\HaphpyBirthdayBundle\Service\FileAttacher
        arguments: [@haphpy.path_generator]

    haphpy.contribution_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AFUP\HaphpyBirthdayBundle\Entity\Contribution

    haphpy.pugs:
        class: AFUP\HaphpyBirthdayBundle\Model\Pugs
        arguments: ["%pug_list%"]

    haphpy.gauge:
        class: AFUP\HaphpyBirthdayBundle\Model\Gauge
        arguments: [@haphpy.contribution_repository, @haphpy.pugs, "%haphpy_steps%"]

    haphy.param_converter.public_contribution:
        class: AFUP\HaphpyBirthdayBundle\ParamConverter\PublicContributionParamConverter
        tags:
            - { name: request.param_converter, converter: public_contribution }
        calls:
            - [ setEntityManager, [@doctrine] ]
